name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push_swap-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .push_swapChecker
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y make gcc valgrind

      - name: Run tests
        run: bash run.sh --show-valgrind